### ISSUE TITLE
imap disconnected every few hours

### ISSUE THREAD

**Issue by Sureshkumars** [ImTheDeveloper/mail-listener-fixed#1]
Is there a way to prolong the life of the mail listener connection without having to refresh the code every few hours? I notice that the mail listener disconnects after a while of no traffic.

**Comment by ImTheDeveloper** [comment]
@Sureshkumars I left a comment on the library this is forked from here https://github.com/chirag04/mail-listener2/issues/54#issuecomment-299415169

As you say there seems to be a disconnect error and I cant work out why.

**Comment by Sureshkumars** [comment]
@Hardware-Hacks Is there any sample workaround for handling this?

**Comment by ImTheDeveloper** [comment]
@Sureshkumars There's a hacky fix here: https://github.com/chirag04/mail-listener2/issues/54#issuecomment-299414382 essentially killing the process when there is a disconnect. As per my response, I've moved onto using context.io for linking to gmail as its much more stable.

**Comment by Sureshkumars** [comment]
@ImTheDeveloper I fixed the issue with the same process. I guess the issue might be due to the default connection timeout of node-imap client ? 10000 seconds

**Comment by ImTheDeveloper** [comment]
I tried to change that but had no success 😣Did altering that time work for you? You can go into your node modules folder and change the idle time in that package after install to check
